from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.index, name="chat_home"),
    path("api/ask-code/", views.ask_code, name="ask_code"),
    path("api/models/", views.model_list, name="model_list"),
    path("api/ollama/settings/", views.ollama_settings, name="ollama_settings"),
    path("api/ollama/models/action/", views.ollama_model_action, name="ollama_model_action"),
    path("api/sessions/", views.session_list, name="session_list"),
    path("api/session/<int:session_id>/manage/", views.manage_session, name="manage_session"),
    path("api/search/", views.knowledge_search, name="knowledge_search"),
    path("api/project/", views.project_documents, name="project_documents"),
    path("api/project/<int:document_id>/", views.project_document_delete, name="project_document_delete"),
    path("api/project/<int:document_id>/content/", views.project_document_content, name="project_document_content"),
    path("api/project/<int:document_id>/reindex/", views.project_document_reindex, name="project_document_reindex"),
    path("api/execute/", views.execute_code, name="execute_code"),
    path("api/agent/plan/", views.agent_plan, name="agent_plan"),
    path("api/agent/task/<int:task_id>/", views.agent_task, name="agent_task"),
    path("api/mcp/connectors/", views.mcp_connectors, name="mcp_connectors"),
    path("api/mcp/connectors/<int:connector_id>/", views.mcp_connector_delete, name="mcp_connector_delete"),
    path("api/mcp/", views.mcp_rpc, name="mcp_rpc"),
    path("api/analyze/", views.quality_analyze, name="quality_analyze"),
    path("api/security/scan/", views.security_scan, name="security_scan"),
    path("api/tests/generate/", views.generate_tests, name="generate_tests"),
    path("api/tests/run/", views.run_tests, name="run_tests"),
    path("api/patch/preview/", views.preview_patch, name="preview_patch"),
    path("api/git/status/", views.git_status, name="git_status"),
    path("api/git/diff/", views.git_diff, name="git_diff"),
    path("api/git/stage/", views.git_stage, name="git_stage"),
    path("api/git/commit/", views.git_commit, name="git_commit"),
    path("api/remote/settings/", views.remote_git_settings, name="remote_git_settings"),
    path("api/remote/repositories/", views.remote_repositories, name="remote_repositories"),
    path("api/remote/issues/", views.remote_issues, name="remote_issues"),
    path("api/remote/pull-request/", views.remote_pull_request, name="remote_pull_request"),
    path("api/cli/ask/", views.cli_ask, name="cli_ask"),
    path("api/session/<int:session_id>/", views.session_messages, name="session_messages"),
    path("api/session/<int:session_id>/revisions/", views.session_revisions, name="session_revisions"),
    path("api/session/<int:session_id>/export/", views.export_session, name="export_session"),
]
