# Generated by Django 5.2.15 on 2026-06-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("preference", "Preference"),
                            ("project_rule", "Project Rule"),
                            ("bug_fix", "Bug Fix"),
                            ("coding_pattern", "Coding Pattern"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("importance", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("filename", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("manual", "Manual"),
                            ("project", "Project Folder"),
                        ],
                        default="upload",
                        max_length=30,
                    ),
                ),
                ("language", models.CharField(default="auto", max_length=50)),
                ("original_text", models.TextField()),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocalModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("temperature", models.FloatField(default=0.2)),
                ("top_p", models.FloatField(default=0.9)),
                ("max_context_chars", models.IntegerField(default=24000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="prompt_tokens_estimate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="response_time_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="model_name",
            field=models.CharField(default="qwen2.5-coder:1.5b", max_length=100),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="filename",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("correction", "Correction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("correction_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chat.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruction", models.TextField()),
                ("input_text", models.TextField(blank=True, null=True)),
                ("expected_output", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("exported", "Exported"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.chatmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("content", models.TextField()),
                ("language", models.CharField(default="auto", max_length=50)),
                ("summary", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="chat.knowledgedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="chat_knowle_documen_c38bec_idx",
                    ),
                    models.Index(
                        fields=["language"], name="chat_knowle_languag_15de5b_idx"
                    ),
                ],
            },
        ),
    ]
