# Generated by Django 5.2.15 on 2026-09-28 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatsession_owner_knowledgedocument_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_message_id", models.IntegerField()),
                ("branch_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
