# Generated by Django 5.2.15 on 2026-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversationrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
