# Generated by Django 5.2.1 on 2026-09-28 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatsession_is_archived_chatsession_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOllamaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_url",
                    models.URLField(default="http://127.0.0.1:11434", max_length=300),
                ),
                (
                    "default_model",
                    models.CharField(default="qwen2.5-coder:1.5b", max_length=100),
                ),
                ("temperature", models.FloatField(default=0.2)),
                ("top_p", models.FloatField(default=0.9)),
                ("max_context_chars", models.IntegerField(default=24000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ollama_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
