# Generated by Django 5.2.1 on 2026-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_mcpconnector_mcptoolcall"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="control_state",
            field=models.CharField(default="ready", max_length=20),
        ),
        migrations.AddField(
            model_name="agenttask",
            name="logs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="agenttask",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agenttask",
            name="source_branch",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
