# Generated by Django 5.2.1 on 2026-09-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_agenttask_control_state_agenttask_logs_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(default="chat", max_length=60)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("input_chars", models.PositiveIntegerField(default=0)),
                ("output_chars", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
