# Generated by Django 5.2.1 on 2026-09-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_workspace_auditevent_workspacemembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspacePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_approval_for_git", models.BooleanField(default=True)),
                ("require_approval_for_tools", models.BooleanField(default=True)),
                ("require_approval_for_deploy", models.BooleanField(default=True)),
                ("require_tests", models.BooleanField(default=True)),
                ("allow_external_connectors", models.BooleanField(default=False)),
                ("audit_retention_days", models.PositiveIntegerField(default=90)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="chat.workspace",
                    ),
                ),
            ],
        ),
    ]
