# Generated by Django 5.2.1 on 2026-09-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_evaluationrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correctness", models.PositiveIntegerField(default=0)),
                ("relevance", models.PositiveIntegerField(default=0)),
                ("completeness", models.PositiveIntegerField(default=0)),
                ("safety", models.PositiveIntegerField(default=0)),
                ("overall", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("method", models.CharField(default="automatic", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="chat.evaluationrun",
                    ),
                ),
            ],
        ),
    ]
