# Generated by Django 5.2.15 on 2026-09-29 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_agentjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryProvisioningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("action", models.CharField(max_length=30)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provisioning_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_events",
                        to="chat.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseIdentityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("oidc", "OIDC"), ("saml", "SAML")],
                        default="oidc",
                        max_length=10,
                    ),
                ),
                ("issuer_url", models.URLField(blank=True, default="")),
                ("client_id", models.CharField(blank=True, default="", max_length=200)),
                (
                    "allowed_domains",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("enforce_sso", models.BooleanField(default=False)),
                ("scim_enabled", models.BooleanField(default=False)),
                (
                    "scim_token_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_config",
                        to="chat.workspace",
                    ),
                ),
            ],
        ),
    ]
