# Generated by Django 5.2.15 on 2026-09-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_directoryprovisioningevent_enterpriseidentityconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseidentityconfig",
            name="saml_entrypoint_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
