# Generated by Django 5.2.15 on 2026-10-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_privacypreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgechunk",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
