# Generated by Django 5.2.15 on 2026-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_knowledgechunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="context_message_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="context_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="context_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
