# Generated by Django 5.2.15 on 2026-10-01 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_chatsession_context_message_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("read_only", "Read only"),
                            ("developer", "Developer"),
                            ("unrestricted", "Unrestricted"),
                        ],
                        default="developer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("require_confirmation", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="unique_user_permission_profile"
                    )
                ],
            },
        ),
    ]
