# Generated by Django 5.2.15 on 2026-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_permissionprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userollamasettings",
            name="runtime",
            field=models.CharField(default="ollama", max_length=20),
        ),
    ]
