# Generated by Django 5.2.15 on 2026-10-01 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_agentworktree"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "retrieval_mode",
                    models.CharField(
                        choices=[("hybrid", "Hybrid RAG"), ("full", "Full document")],
                        default="hybrid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeCollectionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.knowledgecollection",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="chat.knowledgedocument",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="knowledgecollection",
            name="documents",
            field=models.ManyToManyField(
                related_name="collections",
                through="chat.KnowledgeCollectionDocument",
                to="chat.knowledgedocument",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgecollectiondocument",
            constraint=models.UniqueConstraint(
                fields=("collection", "document"), name="unique_collection_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgecollection",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_owner_collection_name"
            ),
        ),
    ]
