# Generated by Django 5.2.15 on 2026-10-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_knowledgecollection_knowledgecollectiondocument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("kind", models.CharField(max_length=40)),
                ("line_start", models.PositiveIntegerField(default=1)),
                ("line_end", models.PositiveIntegerField(default=1)),
                ("signature", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbols",
                        to="chat.knowledgedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="chat_codesy_name_85484d_idx"),
                    models.Index(fields=["kind"], name="chat_codesy_kind_f66d15_idx"),
                ],
            },
        ),
    ]
