# Generated by Django 5.2.1 on 2026-10-01 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0032_codesymbol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopedMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("project", "Project"),
                            ("session", "Conversation"),
                            ("workspace", "Workspace"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("scope_key", models.CharField(blank=True, default="", max_length=240)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("source", models.CharField(default="user", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
