# Generated by Django 5.2.1 on 2026-10-01 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0033_scopedmemory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runtime", models.CharField(default="local", max_length=20)),
                ("method", models.CharField(default="GET", max_length=12)),
                ("endpoint", models.CharField(max_length=400)),
                ("purpose", models.CharField(default="local runtime", max_length=80)),
                ("allowed", models.BooleanField(default=True)),
                ("response_status", models.PositiveIntegerField(default=0)),
                ("request_chars", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
