# Generated by Django 5.2.1 on 2026-10-01 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_networkledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("reindex", "Re-index project files"),
                            ("health", "Runtime health check"),
                            ("benchmark", "Model benchmark"),
                            ("backup", "Local backup reminder"),
                            ("tests", "Run project tests"),
                        ],
                        default="health",
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("interval_minutes", models.PositiveIntegerField(default=60)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_at", "-id"],
            },
        ),
    ]
