# Generated by Django 5.2.1 on 2026-10-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0035_scheduledtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("heading", "Heading"),
                            ("table", "Table"),
                            ("paragraph", "Paragraph"),
                        ],
                        default="paragraph",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("content", models.TextField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="chat.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["document", "page_number"],
                        name="chat_docume_documen_918824_idx",
                    ),
                    models.Index(
                        fields=["section_type"], name="chat_docume_section_a0542c_idx"
                    ),
                ],
            },
        ),
    ]
