# Generated by Django 5.2.1 on 2026-10-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_documentsection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runtime", models.CharField(default="ollama", max_length=20)),
                ("model_name", models.CharField(max_length=160)),
                ("capabilities", models.JSONField(default=dict)),
                ("hardware", models.JSONField(default=dict)),
                ("source", models.CharField(default="inferred", max_length=30)),
                ("probed_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_capabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["model_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "runtime", "model_name"),
                        name="unique_model_capability",
                    )
                ],
            },
        ),
    ]
