# Generated by Django 5.2.1 on 2026-10-05 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0038_mcptask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolSecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("require_confirmation", models.BooleanField(default=True)),
                ("allowed_roots", models.JSONField(blank=True, default=list)),
                ("network_allowed", models.BooleanField(default=False)),
                ("max_calls_per_minute", models.PositiveIntegerField(default=30)),
                (
                    "signed_manifest_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_security_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "tool_name"),
                        name="unique_tool_security_policy",
                    )
                ],
            },
        ),
    ]
