# Generated by Django 5.2.1 on 2026-10-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0039_toolsecuritypolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=240)),
                ("target_name", models.CharField(max_length=240)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("references", "References"),
                            ("imports", "Imports"),
                            ("route", "Route"),
                            ("test", "Test"),
                            ("depends_on", "Depends on"),
                        ],
                        default="references",
                        max_length=30,
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="chat.knowledgedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_name"], name="chat_codere_source__918c39_idx"
                    ),
                    models.Index(
                        fields=["target_name"], name="chat_codere_target__90647c_idx"
                    ),
                    models.Index(
                        fields=["relation_type"], name="chat_codere_relatio_07f8db_idx"
                    ),
                ],
            },
        ),
    ]
